### ISSUE TITLE
gradle build not working

### ISSUE THREAD

**Issue by ayazbekobbelek** [BME-MIT-IET/ivt-hw-2023-maddevs#1]
When you run `gradle jar` or `gradle test` getting the following error:
```
Where:
Build file '/Users/belekayazbekov/Homeworks/Integration/ivt-hw-2023-maddevs/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating root project 'ivt-hw-2023-maddevs'.
> Plugin with id 'maven' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 547ms 
```

This is happening probably because this project was created 4 years ago and uses some outdated version of some tools

**Comment by abdelski** [comment]
@ayazbekobbelek Seems like you already addressed this issue, right?

**Comment by ayazbekobbelek** [comment]
Yep, after some investigation I found out that some dependencies for the current version of gradle are outdated and not available anymore. I decided to update the Gradle 2 to latest Gradle 8. This update required changing some configurations in `build.gradle` because some of them were removed since Gradle 2.
